AWSTemplateFormatVersion: '2010-09-09'
Description: Code Pipeline implementation connected to merchant working capital for deploy with cloudformation.
Parameters:
  Environment:
    Type: String
    Default: dev
  AppName:
    Type: String
    Description: The project Name.
    Default: merchantcapital
  PrincipalTemplate:
    Type: String
    Default: ProjectTemplate.json
  ArtifactName:
    Type: String
    Default: projectTemplate.zip
  BucketArtifactName:
    Type: String
    Description: Optional bucket name if you pass this parameter the bucket will be exist  at the accounts else this template create a new bucket
    Default: ''
  Country:
    Type: String
    Description: >-
      country ISO code as described in the ISO 3166 international standard
      (ALPHA-2).
    MinLength: 2
    MaxLength: 2
    AllowedPattern: "^[A-Z]*$"
    ConstraintDescription: Malformed input-Parameter Country must only contain uppercase
  CountryLowercase:
    Type: String
    Description: >-
      country ISO code as described in the ISO 3166 international standard
      (ALPHA-2).
    MinLength: 2
    MaxLength: 2
    AllowedPattern: "^[a-z]*$"
    ConstraintDescription: Malformed input-Parameter CountryLowercase must only contain lowercase
  DomainName:
    Type: String
  SubnetsIds:
    Type: AWS::SSM::Parameter::Value<String>
  SecurityGroup:
    Type: AWS::SSM::Parameter::Value<String>
  MtsConnectorHost:
    Type: String
Conditions:
  CreateBucketArtifacts: !Equals
    - !Ref 'BucketArtifactName'
    - ''
Resources:
  RoleCodePipeline:
    Type: AWS::IAM::Role
    Properties:
      RoleName: !Sub '${Environment}-${CountryLowercase}-${AppName}-pipeline-role'
      Path: /
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service:
                - codepipeline.amazonaws.com
            Action: sts:AssumeRole
      Policies:
        - PolicyName: !Sub '${Environment}-${CountryLowercase}-${AppName}-pipeline-policy'
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action:
                  - iam:PassRole
                Resource: '*'
              - Effect: Allow
                Action:
                  - ec2:*
                  - cloudwatch:*
                  - cloudformation:*
                  - rds:*
                  - codebuild:*
                Resource: '*'
              - Effect: Allow
                Action: s3:*
                Resource: !If
                  - CreateBucketArtifacts
                  - !GetAtt
                    - BucketArtifactStore
                    - Arn
                  - !Sub "arn:aws:s3:::${BucketArtifactName}"
  RoleCloudFormation:
    Type: AWS::IAM::Role
    Properties:
      RoleName: !Sub '${Environment}-${CountryLowercase}-${AppName}-cloudformation-role'
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service:
                - cloudformation.amazonaws.com
            Action: sts:AssumeRole
      Path: /
      Policies:
        - PolicyName: !Sub '${Environment}-${CountryLowercase}-${AppName}-cloudformation-policy'
          PolicyDocument:
            Statement:
              - Sid: VisualEditor0
                Effect: Allow
                Action:
                  - s3:*
                  - waf:*
                  - iam:*
                  - ssm:*
                  - ec2:*
                  - acm:*
                  - logs:*
                  - wafv2:*
                  - lambda:*
                  - appsync:*
                  - dynamodb:*
                  - apigateway:*
                  - codedeploy:*
                  - route53:*
                  - cloudfront:*
                  - cognito-idp:*
                  - waf-regional:*
                  - cloudformation:*
                  - cognito-identity:*
                  - elasticloadbalancing:*
                  - organizations:ListRoots
                  - organizations:ListParents
                  - organizations:ListPolicies
                  - organizations:ListChildren
                  - organizations:DescribePolicy
                  - organizations:DescribeAccount
                  - organizations:DescribeOrganization
                  - organizations:ListTargetsForPolicy
                  - organizations:ListPoliciesForTarget
                  - organizations:DescribeOrganizationalUnit
                Resource: '*'
            Version: '2012-10-17'
  BucketArtifactStore:
    Condition: CreateBucketArtifacts
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Sub '${Environment}-${CountryLowercase}-${AppName}-artifacts-${AWS::AccountId}'
      PublicAccessBlockConfiguration:
        BlockPublicAcls: true
        BlockPublicPolicy: true
        IgnorePublicAcls: true
        RestrictPublicBuckets: true
      VersioningConfiguration:
        Status: Enabled
      BucketEncryption:
        ServerSideEncryptionConfiguration:
          - ServerSideEncryptionByDefault:
              SSEAlgorithm: AES256
  Pipeline:
    Type: AWS::CodePipeline::Pipeline
    Properties:
      Name: !Sub '${AppName}-${CountryLowercase}-pipeline'
      RoleArn: !GetAtt 'RoleCodePipeline.Arn'
      ArtifactStore:
        Type: S3
        Location: !If
          - CreateBucketArtifacts
          - !Ref 'BucketArtifactStore'
          - !Ref 'BucketArtifactName'
      Stages:
        - Name: Source
          Actions:
            - Name: !Sub 'Source-${AppName}'
              ActionTypeId:
                Category: Source
                Owner: AWS
                Version: 1
                Provider: S3
              OutputArtifacts:
                - Name: SourceOutput
              Configuration:
                S3Bucket: !If
                  - CreateBucketArtifacts
                  - !Ref 'BucketArtifactStore'
                  - !Ref 'BucketArtifactName'
                S3ObjectKey: !Sub "deploys/${AppName}/${CountryLowercase}/${ArtifactName}"
                PollForSourceChanges: true
              RunOrder: 1
        - Name: Deploy
          Actions:
            - Name: CreateChangeSet
              ActionTypeId:
                Category: Deploy
                Owner: AWS
                Version: 1
                Provider: CloudFormation
              Configuration:
                ActionMode: CHANGE_SET_REPLACE
                ChangeSetName: !Join
                  - "-"
                  - - !Ref Environment
                    - !Ref CountryLowercase
                    - !Ref AppName
                    - changeSet
                StackName: !Join
                  - "-"
                  - - !Ref Environment
                    - !Ref CountryLowercase
                    - !Ref AppName
                    - stack
                Capabilities: CAPABILITY_IAM,CAPABILITY_NAMED_IAM,CAPABILITY_AUTO_EXPAND
                TemplatePath: !Join
                  - "::"
                  - - SourceOutput
                    - !Ref PrincipalTemplate
                RoleArn: !GetAtt 'RoleCloudFormation.Arn'
                ParameterOverrides: !Sub
                  - >-
                    {"Environment": "${Environment}",
                     "ArtifactsBucket": "${ArtifactsBucket}",
                     "AppName": "${AppName}",
                     "Country": "${Country}",
                     "FolderCountry": "${FolderCountry}",
                     "DomainName": "${DomainName}",
                     "MtsHost": "${MtsHost}",
                     "SubnetsIds": "${SubnetsIds}",
                     "SecurityGroup": "${SecurityGroup}"
                    }
                  - Environment: !Ref Environment
                    ArtifactsBucket: !If
                      - CreateBucketArtifacts
                      - !Ref BucketArtifactStore
                      - !Ref BucketArtifactName
                    projectName: !Ref AppName
                    Country: !Ref CountryLowercase
                    DomainName: !Sub >-
                      /${Environment}/${CountryLowercase}/api/connector/domain/name
                    FolderCountry: !Ref Country
                    MtsHost: !Ref MtsConnectorHost
                    SubnetsIds: !Ref SubnetsIds
                    SecurityGroup: !Ref SecurityGroup
              RunOrder: 1
              InputArtifacts:
                - Name: SourceOutput
            - Name: ChangeSetExecute
              ActionTypeId:
                Category: Deploy
                Owner: AWS
                Version: 1
                Provider: CloudFormation
              Configuration:
                ActionMode: CHANGE_SET_EXECUTE
                ChangeSetName: !Join
                  - "-"
                  - - !Ref Environment
                    - !Ref CountryLowercase
                    - !Ref AppName
                    - changeSet
                StackName: !Join
                  - "-"
                  - - !Ref Environment
                    - !Ref CountryLowercase
                    - !Ref AppName
                    - stack
              RunOrder: 2
              InputArtifacts:
                - Name: SourceOutput
