Description: WebACL for Integration Transmit API Gateway and rules definition
Parameters:
  Environment:
    Description: Environment name
    Type: String
  ApiID:
    Description: API Gateway stack Name for import Values
    Type: String
  ApiDeployVersion:
    Description: API Gateway stack Name for import Values
    Type: String
  Country:
    Description: Country app
    Type: String
Resources:
  WebACL:
    Type: AWS::WAFv2::WebACL
    Properties:
      Name:
        Fn::Sub: ${Environment}-${Country}-IntegratorWaf
      Scope: REGIONAL
      Description: This is a Transmit API Gateway WebACL
      DefaultAction:
        Allow: {}
      VisibilityConfig:
        SampledRequestsEnabled: true
        CloudWatchMetricsEnabled: true
        MetricName: WebACLMetric
      Rules:
        - Name: RuleWithAWSManagedRule
          Priority: 0
          OverrideAction:
            Count: {}
          VisibilityConfig:
            SampledRequestsEnabled: true
            CloudWatchMetricsEnabled: true
            MetricName: RuleWithAWSManagedRulesMetric
          Statement:
            ManagedRuleGroupStatement:
              VendorName: AWS
              Name: AWSManagedRulesCommonRuleSet
              ExcludedRules: []
        - Name: BlockXssAttackRule
          Priority: 1
          Action:
            Block: {}
          VisibilityConfig:
            SampledRequestsEnabled: true
            CloudWatchMetricsEnabled: true
            MetricName: BlockXssAttackMetric
          Statement:
            XssMatchStatement:
              FieldToMatch:
                AllQueryArguments: {}
              TextTransformations:
                - Priority: 0
                  Type: HTML_ENTITY_DECODE
                - Priority: 1
                  Type: URL_DECODE
        - Name: SqlInjectionMatchRule
          Priority: 2
          Action:
            Block: {}
          VisibilityConfig:
            SampledRequestsEnabled: true
            CloudWatchMetricsEnabled: true
            MetricName: SqliMatchStatementMetric
          Statement:
            SqliMatchStatement:
              FieldToMatch:
                AllQueryArguments: {}
              TextTransformations:
                - Priority: 0
                  Type: HTML_ENTITY_DECODE
                - Priority: 1
                  Type: URL_DECODE
        - Name: SizeConstraintMatchRule
          Priority: 3
          Action:
            Block: {}
          VisibilityConfig:
            SampledRequestsEnabled: true
            CloudWatchMetricsEnabled: true
            MetricName: SizeConstraintStatementMetric
          Statement:
            SizeConstraintStatement:
              ComparisonOperator: GT
              Size: 500
              FieldToMatch:
                AllQueryArguments: {}
              TextTransformations:
                - Priority: 0
                  Type: HTML_ENTITY_DECODE
                - Priority: 1
                  Type: URL_DECODE
  WebACLAssociation:
    Type: AWS::WAFv2::WebACLAssociation
    Properties:
      WebACLArn:
        Fn::GetAtt:
          - WebACL
          - Arn
      ResourceArn:
        Fn::Sub: arn:aws:apigateway:${AWS::Region}::/restapis/${ApiID}/stages/${ApiDeployVersion}
Outputs:
  WebACLArn:
    Description: Arn of WAF ACL to Application API Gateway
    Value:
      Fn::GetAtt:
        - WebACL
        - Arn
